### PR TITLE
add option to change cpuquota on plugin page

### PR DESCRIPTION
**Pull request by awinnen**
ref: http://forums.openmediavault.org/index.php/Thread/550-openmediavault-jdownloader-Plugin/?postID=117991#post117991

### CODE REVIEW

**Comment by cptjhmiller** [comment]
I have merged it but holding off making the next version.
Want to see reasons for removing the download folder option from the plugin page.

**Comment by Skaronator** [comment]
@cptjhmiller Somehow this doesn't work correctly for me?


I set it to 50% and according to `htop` it is round about 50% (20%+30%) but if you look on my cores they are just about ~5%? Have I misunderstood something?

image

**Comment by cptjhmiller** [comment]
That needs a little more work, it uses the value from a single core and not all cores so when it's load on 1 core gets too high it will throttle down.
I will make the changes this weekend as others have been asking for it as well.

**Comment by awinnen** [comment]
i have the changes ready for some months but never released them -.-
#10 i sent you a pull request.

**Comment by Skaronator** [comment]
Oh, thanks to you both. @Naffi & @cptjhmiller

**Comment by cptjhmiller** [comment]
Thanks @Naffi I will publish the request over the weekend, any other changes you have that other may like?

**Pull request merged**
